export const dummyProducts = [
  {
    id: "1",
    name: "Luxury Foundation Set",
    description: "Premium full-coverage foundation with SPF protection and long-lasting formula",
    price: 4500,
    image: "/luxury-foundation-set.jpg",
    category: "women" as const,
    collection: "Makeup Essentials",
    type: "makeup" as const,
    in_stock: true,
    sizes: ["30ml", "50ml"],
    colors: ["Fair", "Medium", "Deep"],
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Designer Eyeshadow Palette",
    description: "Professional 12-shade eyeshadow palette with matte and shimmer finishes",
    price: 6500,
    image: "/designer-eyeshadow-palette.jpg",
    category: "women" as const,
    collection: "Eye Makeup",
    type: "makeup" as const,
    in_stock: true,
    sizes: ["One Size"],
    colors: ["Neutral", "Warm", "Cool"],
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Premium Skincare Set",
    description: "Complete 5-step skincare routine with anti-aging properties",
    price: 2500,
    image: "/premium-skincare-set.jpg",
    category: "women" as const,
    collection: "Skincare Essentials",
    type: "skincare" as const,
    in_stock: true,
    sizes: ["30ml", "50ml", "100ml"],
    colors: ["Original", "Sensitive", "Oily Skin"],
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Luxury Lipstick Collection",
    description: "High-pigment lipstick with moisturizing formula and 8-hour wear",
    price: 1800,
    image: "/luxury-lipstick-collection.jpg",
    category: "women" as const,
    collection: "Lip Makeup",
    type: "makeup" as const,
    in_stock: true,
    sizes: ["3.5g"],
    colors: ["Red", "Pink", "Nude", "Berry"],
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Signature Perfume",
    description: "Elegant floral fragrance with notes of jasmine, rose, and vanilla",
    price: 8500,
    image: "/signature-perfume.jpg",
    category: "women" as const,
    collection: "Fragrances",
    type: "fragrances" as const,
    in_stock: true,
    sizes: ["50ml", "100ml"],
    colors: ["Original"],
    created_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Anti-Aging Serum",
    description: "Advanced retinol serum for reducing fine lines and wrinkles",
    price: 3200,
    image: "/anti-aging-serum.jpg",
    category: "women" as const,
    collection: "Anti-Aging",
    type: "skincare" as const,
    in_stock: true,
    sizes: ["30ml", "50ml"],
    colors: ["Original"],
    created_at: new Date().toISOString(),
  },
]

export const testimonials = [
  {
    name: "Fatima Khan",
    text: "Glamour Cosmetics has the most amazing makeup collection! The quality is exceptional and the customer service is outstanding.",
    rating: 5,
  },
  {
    name: "Ayesha Ahmed",
    text: "I love the skincare products from Glamour. They work perfectly and my skin has never looked better!",
    rating: 5,
  },
  {
    name: "Zainab Hassan",
    text: "The fragrances are absolutely divine. I've been a loyal customer for years now.",
    rating: 5,
  },
]

export const whyChooseUs = [
  {
    title: "Premium Quality",
    description: "We use only the finest ingredients and materials for our beauty products",
    icon: "✨",
  },
  {
    title: "Expert Formulation",
    description: "Each product is carefully formulated by skilled cosmetic chemists with years of experience",
    icon: "🧪",
  },
  {
    title: "Skin-Friendly",
    description: "All products are dermatologically tested and suitable for all skin types",
    icon: "💆‍♀️",
  },
  {
    title: "Fast Delivery",
    description: "Quick and reliable delivery across the country",
    icon: "🚚",
  },
]
